# BiomassBoiler FMU Project Configuration

project:
  name: "BiomassBoiler_DigitalTwin"
  description: "Biomass boiler physics model for digital twin simulation"

modelica:
  model_class: "BiomassBoiler.DigitalTwin"

files:
  main: "BiomassBoiler.mo"

external_libraries: []

fmu:
  type: "cs"
  version: "2.0"
  platform: "static"
  output_name: "DigitalTwin"

interface:
  inputs: []
  outputs: []
